### ISSUE TITLE
About lora hyperparameters.

### ISSUE THREAD

**Issue by Yingshu-Li** [function2-llx/MMMM#12]
I noticed in your paper that you set the LoRA rank at 64 and alpha at 8. However, previous studies commonly recommend setting alpha at twice the rank. Could you explain if there was specific reasoning or insight within the medical domain that influenced this setting?

**Comment by function2-llx** [comment]
Hi, thank you for your interest here. We use rsLoRA, where the weight is scaled with the squared root of the rank. And we choose alpha proportional to the squared root value of the rank.
